# Generated by Django 5.0.6 on 2024-06-21 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='complete_name',
        ),
        migrations.AlterField(
            model_name='userconnections',
            name='firstuser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authapp.connectionrequest', verbose_name='first_user'),
        ),
        migrations.RemoveField(
            model_name='userconnections',
            name='seconduser',
        ),
        migrations.AddField(
            model_name='userconnections',
            name='seconduser',
            field=models.ManyToManyField(blank=True, default=None, related_name='second_user', to='authapp.connectionrequest'),
        ),
    ]
