# Generated by Django 5.0.6 on 2024-06-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_userconnections_firstuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconnections',
            name='connection',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
