# Generated by Django 5.0.6 on 2024-07-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_userconnections_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectionrequest',
            name='status',
        ),
        migrations.AlterField(
            model_name='userconnections',
            name='connection',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
