# Generated by Django 5.0.6 on 2024-08-22 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=400)),
                ('message_creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_creator', to=settings.AUTH_USER_MODEL)),
                ('post_foreign_key', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_id', to='authapp.post')),
            ],
        ),
    ]
