# Generated by Django 5.0.6 on 2024-06-22 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_remove_user_complete_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconnections',
            name='firstuser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='first_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='userconnections',
            name='seconduser',
        ),
        migrations.AddField(
            model_name='userconnections',
            name='seconduser',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='second_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
