# Generated by Django 5.0.6 on 2024-06-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_userconnections_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconnections',
            name='connection',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
