# Generated by Django 5.0.6 on 2024-06-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='static/image/icons/avatar.svg', null=True, upload_to='static/image/icons/'),
        ),
    ]
