# Generated by Django 5.0.6 on 2024-06-10 20:26

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_alter_user_avatar_alter_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('avatar', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=image_cropping.fields.ImageCropField(blank=True, default='static/images/icons/avatar.svg', null=True, upload_to='static/images/icons/'),
        ),
    ]
