# Generated by Django 5.0.6 on 2024-06-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='static/images/icons/avatar.svg', upload_to='static/images/icons/'),
        ),
    ]
