# Generated by Django 5.0.6 on 2024-06-11 20:35

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=image_cropping.fields.ImageCropField(blank=True, default='static/images/icons/avatar.svg', null=True, upload_to='static/images/icons/'),
        ),
    ]
