# Generated by Django 5.0.6 on 2024-06-11 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0016_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cropping',
        ),
    ]
