# Generated by Django 5.0.6 on 2024-06-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0017_remove_user_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='media/avatar.svg', null=True, upload_to='media/'),
        ),
    ]
