# Generated by Django 5.0.6 on 2024-06-12 20:40

import authapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0020_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatardefault.png', null=True, upload_to=authapp.models.user_directory_path),
        ),
    ]
