# Generated by Django 5.0.6 on 2024-06-17 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0024_user_age_user_attractedto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
