# Generated by Django 5.0.6 on 2024-06-19 00:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0026_connectionrequest_userconnections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconnections',
            name='connectionsUser',
            field=models.ManyToManyField(blank=True, related_name='connections', to=settings.AUTH_USER_MODEL),
        ),
    ]
