# Generated by Django 5.0.6 on 2024-06-19 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0027_alter_userconnections_connectionsuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconnections',
            name='connectionsUser',
        ),
        migrations.RemoveField(
            model_name='userconnections',
            name='user',
        ),
        migrations.AddField(
            model_name='userconnections',
            name='firstuser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authapp.connectionrequest', verbose_name='first_user'),
        ),
        migrations.AddField(
            model_name='userconnections',
            name='seconduser',
            field=models.ManyToManyField(blank=True, default=None, related_name='second_user', to='authapp.connectionrequest'),
        ),
    ]
