# Generated by Django 5.0.6 on 2024-06-20 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0028_remove_userconnections_connectionsuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconnections',
            name='firstuser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='first_user'),
        ),
        migrations.AlterField(
            model_name='userconnections',
            name='seconduser',
            field=models.ManyToManyField(blank=True, default=None, related_name='second_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
