# Generated by Django 5.0.6 on 2024-06-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0029_alter_userconnections_firstuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconnections',
            name='connection',
            field=models.TextField(default='<django.db.models.fields.related.ForeignKey>-<django.db.models.fields.related.ManyToManyField>'),
        ),
    ]
